mongock:
  migrationScanPackage: com.technokratos.migration
  transaction-enabled: false

spring:
  application:
    name: location-service
  cloud:
    consul:
      discovery:
        enabled: true
      host: consul
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8080/.well-known/jwks.json

springdoc:
  api-docs:
    path: /api/v1/location-service/v3/api-docs