spring:

  application:
    name: gateway-service

  cloud:
    consul:
      discovery:
        enabled: true
      host: consul

    gateway:

      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user-service/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/event-service/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth-service/**

        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/api/v1/location-service/**


springdoc:
  api-docs-urls: >
    http://user-service:8080/api/v1/user-service/v3/api-docs,
    http://event-service:8080/api/v1/event-service/v3/api-docs,
    http://auth-service:8080/api/v1/auth-service/v3/api-docs,
    http://location-service:8080/api/v1/location-service/v3/api-docs


frontend:
  domain: ${FRONTEND_DOMAIN}