jwt:
  access-token-validity: 30
  refresh-token-validity: 1440
  private-secret-key: ****
  public-secret-key: ****

spring:

  data:
    redis:
      host: auth-redis
      port: 6379
      password: password
      database: 0

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ****
            client-secret: ****
            scope: ****
            redirect-uri: ****
logging:
  level:
    root: debug