spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: mail.eventflow@gmail.com
    password: hgrr vafg yxgr mkle
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: notifications-rabbit
    port: 5672
    username: user
    password: password
    virtual-host: local