spring:

  mail:
    host:
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: notifications-rabbit
    port: 5672
    username: user
    password: password
    virtual-host: local